name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build changed documents
      uses: ./.github/actions/hse-tex-build
      env: 
        CHECK_DIFF: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Documents
        path: .pdf/**/*.pdf
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: '_gh_pages'
    - name: Post diff
      run: ./post-diff.sh
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        DRAFTABLE_API_ID: ${{ secrets.DRAFTABLE_API_ID }}
        DRAFTABLE_API_TOKEN: ${{ secrets.DRAFTABLE_API_TOKEN }}
