name: Build
on:
- push
- pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./.github/actions/hse-tex-build
    - name: Upload artifacts
      uses: hse-tex/upload-artifact@multiple-artifacts
      with:
        path: .pdf/**/*.pdf
